# Generated by Django 3.2.7 on 2021-09-12 01:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.CharField(choices=[('ООО', 'ООО'), ('ОАО', 'ОАО'), ('ЗАО', 'ЗАО'), ('ПАО', 'ПАО')], default='ООО', max_length=3, verbose_name='Company ownership')),
                ('name', models.CharField(max_length=100, verbose_name='Company name')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_Name', models.CharField(max_length=100, verbose_name='Last mame')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Patronymic')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='TestTask.company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Deal name')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='TestTask.contact', verbose_name='Contact')),
            ],
        ),
        migrations.CreateModel(
            name='DealStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Deal stage name')),
                ('probability', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than 0'), django.core.validators.MaxValueValidator(100, message='Value must be less than 100')], verbose_name='Probability of success (0-100%)')),
            ],
        ),
        migrations.CreateModel(
            name='DealStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01, message='Value must be greater than 0')], verbose_name='Amount of successful deal')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], db_index=True, default='RUB', max_length=3, verbose_name='Deal currency')),
                ('estimated_date', models.DateField(db_index=True, verbose_name='Estimated date of deal completion')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Time stamp')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='TestTask.deal', verbose_name='Deal')),
                ('deal_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestTask.dealstage')),
            ],
        ),
    ]
